[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if has('win32')
    let  cmd = 'tools\\udpate-dll-mingw'
  elseif has('win32unix') " for Cygwin
    let cmd = 'make -f make cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#[[plugins]]
#repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'
