[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'
